apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb-service
spec:
  type: ClusterIP
  ports:
  - name: port-influxdb
    port: 8086
  selector:
    app: influxdb
