apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/LOGIN/ft_services/srcs/influxdb/database"