apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-service
spec:
  type: LoadBalancer
  ports:
  - name: port-grafana
    port: 3000
  selector:
    app: grafana
