apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-service
spec:
  type: LoadBalancer
  ports:
  - name: port-phpmyadmin
    port: 5000
  selector:
    app: phpmyadmin