apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress-service
spec:
  type: LoadBalancer
  ports:
  - name: port-wordpress
    port: 5050
  selector:
    app: wordpress
