apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps-service
spec:
  type: LoadBalancer
  ports:
  - name: data
    port: 20
    protocol: TCP
  - name: entry
    port: 21
    protocol: TCP
  selector:
    app: ftps
